#!/usr/bin/env bash

is_prime() {
    num=$1
    if ((num < 2)); then
        return 1
    fi
    for ((i = 2; i <= num / 2; i++)); do
        if ((num % i == 0)); then
            return 1
        fi
    done
    return 0
}

factorize() {
    num=$1
    factors=""
    for ((i = 2; i <= num / 2; i++)); do
        if ((num % i == 0)); then
            if is_prime "$i"; then
                factors+="$i*"
            fi
        fi
    done
    factors+="$(($num / $i))"
    echo "$factors"
}

if [ $# -ne 1 ]; then
    echo "Usage: rsa <file>"
    exit 1
else
    while read -r num; do
        factors=$(factorize "$num")
        echo "$num=$factors"
    done < "$1"
fi

